### ISSUE TITLE
Can't make migration

### ISSUE THREAD

**Issue by TheDreamCatcher** [ruturajmaniyar/yii2-audit-log#1]
Hi! I did all from instruction and got

php yii migrate --migration-path "vendor/ruturajmaniyar/yii2-audit-log/src/migrations/"
Yii Migration Tool (based on Yii v2.0.30)

Total 1 new migration to be applied:
	m190612_092611_tbl_audit_entry

Apply the above migration? (yes|no) [no]:y
*** applying m190612_092611_tbl_audit_entry
Error: Failed to instantiate component or class "m190612_092611_tbl_audit_entry".

After some research found error text in Yii

Class m190612_092611_tbl_audit_entry does not exist

Run "composer dumpa". Not helped

**Comment by ariefbayu** [comment]
the example suggests "@vendor/ruturajmaniyar/" while your executed code only use "vendor/ruturajmaniyar/", might that be the issue?

**Comment by ruturajmaniyar** [comment]
Hi

please use below path for migration

`php yii migrate/up --migration-path "@vendor/ruturajmaniyar/yii2-audit-log/src/migrations/"`

you missed '@' sign in migration path.
